### ISSUE TITLE
Scope incorrectly resolves when query string present

### ISSUE THREAD

**Issue by jasonrm** [npm/npmconf#43]
I think I'm seeing an auth issue in npm related to how `getCredentialsByURI` resolves the scope when there is a query string present in the URI.

In npm-registry-client there is [this line](https://github.com/npm/npm-registry-client/blob/7729265d81d4fc6fe3056f770bbfb9010b772241/lib/publish.js#L102) that appends `?write=true` to the registry URI. When it does this, `getCredentialsByURI` no longer returns the needed user/password to auth with the private registry.

I can also resolve the issue by just deleting the addition of `?write=true` to the query string, but I've no idea why it's there to start so that doesn't seem like a great idea.

```javascript
// Pass case
test("get package info URI, without query string", function (t) {
  npmconf.load(common.builtin, function (er, conf) {
    var actual = conf.getCredentialsByURI("https://registry.npmjs.org/foo")
    var expected = {
      scope: '//registry.npmjs.org/',
      password: 'password',
      username: 'username',
      email: 'i@izs.me',
      auth: 'dXNlcm5hbWU6cGFzc3dvcmQ='
    }
    t.same(actual, expected)
    t.end()
  })
})

// Fail case
test("get package info URI, with query string", function (t) {
  npmconf.load(common.builtin, function (er, conf) {
    var actual = conf.getCredentialsByURI("https://registry.npmjs.org/foo?write=true")
    var expected = {
      scope: '//registry.npmjs.org/',
      password: 'password',
      username: 'username',
      email: 'i@izs.me',
      auth: 'dXNlcm5hbWU6cGFzc3dvcmQ='
    }
    t.same(actual, expected)
    t.end()
  })
})
```

**Comment by othiym23** [comment]
This package is deprecated, as its functionality has been reincorporated directly into npm. As such, no further development will happen here. Closing as WONTFIX.
