### ISSUE TITLE
Namespace config options as well for more finegrained control

### ISSUE THREAD

**Issue by kristianmandrup** [npm/npmconf#44]
Please see https://github.com/npm/npm/issues/6073

Would be nice/prefereable if we had `npm.config.local.get("searchParentDir")` so we only do this if the config option is set in the per folder `.npmrc` file.

I assume this could be handled somehow via the type of `addFile`?

https://github.com/npm/npmconf/blob/master/npmconf.js#L131

`conf.addFile(projectConf, 'project')`

Not sure what to do from here...

**Comment by othiym23** [comment]
This package is deprecated, as its functionality has been reincorporated directly into npm. As such, it's not going to see any further development. Closing as WONTFIX.
