### ISSUE TITLE
package.json problem with maven.

### ISSUE THREAD

**Issue by mbelang** [npm/npmconf#58]
Hi,

The declaration of semver version range doesn't work with maven dependency specification so I cannot publish a new version of npmconf.

Could it be possible to declare semver like this: >=2.0.0 <5.0.0.
I'm not sure what is the impact of the change but looking at the npm package.json doc, it would fit my needs and ours as well.

Thx

**Comment by othiym23** [comment]
This project is deprecated, since its functionality has been reincorporated directly into npm itself. As such, it's not going to see any further development. Closing as WONTFIX.
